apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: {{ .Values.postgres.name }}
    {{- include "secrecto.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres
