apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  labels:
    app: {{ .Values.backend.name }}
    {{- include "secrecto.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.backend.secret }}
  {{ $key }}: "{{ $value }}"
{{- end }}
