apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: {{ .Values.backend.name }}
    {{- include "secrecto.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
  type: ClusterIP
