apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.configMapName }}
  labels:
    app: {{ .Values.frontend.name }}
    {{- include "secrecto.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.frontend.config }}
  {{ $key }}: "{{ $value }}"
{{- end }}
